import './globals.css'

import { Kumbh_Sans, Roboto_Mono } from 'next/font/google'

const robotoMono = Roboto_Mono({
	subsets: ['latin'],
	variable: '--font-roboto-mono',
})
const kumbhSans = Kumbh_Sans({
	subsets: ['latin'],
	variable: '--font-kumbh-sans',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className={`${robotoMono.variable} ${kumbhSans.variable} font-sans`}
			>
				{children}
			</body>
		</html>
	)
}
